# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 19:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('default', models.BooleanField(default=False)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_customer', to='eatplusapp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('name', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='image/item/')),
                ('price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('takeout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.IntegerField(choices=[(0, 'radio'), (1, 'select')])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_option', to='eatplusapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('total', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('order_for', models.IntegerField(blank=True, choices=[(1, 'Pick up'), (2, 'Delivery')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Placed'), (3, 'Received'), (4, 'Ready'), (5, 'On the way'), (6, 'Completed'), (7, 'Cancelled')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatplusapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_total', models.IntegerField(default=1)),
                ('choices', models.ManyToManyField(blank=True, related_name='choices_orderitem', to='eatplusapp.Choice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orderitem', to='eatplusapp.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderitem', to='eatplusapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='image/restaurant/')),
                ('restaurant_slug', models.SlugField(max_length=250, unique=True)),
                ('minimum_delivery_order', models.IntegerField(blank=True, null=True)),
                ('delivery_fee', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(blank=True, max_length=4)),
                ('verified', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('boundaries', models.TextField(blank=True)),
                ('referral_code', models.CharField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_restaurant', to='eatplusapp.Address')),
                ('delivery_payment_methods', models.ManyToManyField(blank=True, related_name='delivery_restaurant_payment', to='eatplusapp.PaymentMethod')),
                ('pickup_payment_methods', models.ManyToManyField(blank=True, related_name='pickup_restaurant_payment', to='eatplusapp.PaymentMethod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='eatplusapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatplusapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='eatplusapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='item',
            name='menu_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_section', to='eatplusapp.MenuSection'),
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatplusapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='choice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_choice', to='eatplusapp.Item'),
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_choice', to='eatplusapp.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='menusection',
            unique_together=set([('restaurant', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('menu_section', 'order')]),
        ),
    ]
