# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplusapp', '0003_auto_20171204_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
