# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplusapp', '0005_auto_20171221_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(upload_to='image/customers/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/restaurants/'),
        ),
    ]
