# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatplusapp', '0007_auto_20180120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='eatplusapp.Customer'),
        ),
    ]
